server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./mydb
    username: admin
    password: 14587415
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          reg-client-oidc:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: reg-client-oidc
          reg-client-authorization-code:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: user.read,user.write
            client-name: reg-client-authorization-code
          reg-client-client-credentials:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: user.read,user.write
            client-name: reg-client-client-credentials
          reg-client-device-code:
            provider: spring
            client-id: device-reg-client
            client-authentication-method: none
            authorization-grant-type: urn:ietf:params:oauth:grant-type:device_code
            scope: user.read,user.write
            client-name: reg-client-device-code
        provider:
          spring:
            issuer-uri: http://localhost:9000

sqlrequest:
  findAll: SELECT * FROM userTable
  save: INSERT INTO userTable (firstName,lastName) VALUES (?, ?)
  delete: DELETE FROM userTable WHERE id=?
  getById: SELECT id,firstName,lastName FROM userTable WHERE id = ?
  update: UPDATE userTable SET firstName = ?, lastName = ? WHERE id = ?
  count: SELECT count(*) FROM userTable WHERE id = ?